name: Pull request action

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Build docker image
        run: docker compose -f cicd/docker-compose.yml build ipsw_downloader

      - name: Check python format
        id: format
        run: docker compose -f cicd/docker-compose.yml run --remove-orphans ipsw_downloader black --check -v .

      - name: Comment results on PR
        if: failure()
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X POST \
          -d '{"body":"### Black Lint Results\n```bash\n${{ steps.format.outputs.stdout }}\n```"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

